### ISSUE TITLE
Lider: Definir las tareas de cada uno de los miembros del equipo

### ISSUE THREAD

**Issue by Luiscramirez2021** [Luiscramirez2021/Estaciones_Meteorol-gica#7]
Definir las tareas de cada uno de los miembros del equipo

**Comment by JuanAvilaB** [comment]
correo: juriavbu89@gmail.com

**Comment by EdRiver11** [comment]
edwin_rivera21132@elpoli.edu.co

**Comment by JorgeAndresP** [comment]
Correo Jorge Pacheco: jorgeanpb@gmail.com

**Comment by jdmtn** [comment]
damin_10@gmail.com

**Comment by Luiscramirez2021** [comment]
Carpetas Compartidas
https://drive.google.com/drive/folders/1FJYlCYTOB57VBiWjzphrSCJr7PGxngrQ?usp=sharing
